version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: foosball_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123!
      MYSQL_DATABASE: foosball
      MYSQL_USER: trifork
      MYSQL_PASSWORD: trifork123!
    volumes:
      - ./mysql-data:/var/lib/mysql
