version: "3.8"

services:
  mysql:
    image: postgres:latest
    container_name: foosball_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=foosball
    volumes:
      - db:/var/lib/postgresql/data 


volumes:
  db: