definitions:
  repos.LeaderboardEntry:
    properties:
      loses:
        type: integer
      mmr:
        type: integer
      name:
        type: string
      wins:
        type: integer
    type: object
  view.Match:
    properties:
      team1:
        $ref: '#/definitions/view.MatchTeam'
      team2:
        $ref: '#/definitions/view.MatchTeam'
    required:
    - team1
    - team2
    type: object
  view.MatchDetails:
    properties:
      date:
        type: string
      team1:
        $ref: '#/definitions/view.MatchTeam'
      team2:
        $ref: '#/definitions/view.MatchTeam'
    required:
    - date
    - team1
    - team2
    type: object
  view.MatchTeam:
    properties:
      member1:
        type: string
      member2:
        type: string
      score:
        type: integer
    required:
    - member1
    - member2
    - score
    type: object
info:
  contact: {}
paths:
  /admin/recalculate:
    post:
      consumes:
      - application/json
      description: Start recalculating matches
      produces:
      - application/json
      responses:
        "200":
          description: recalculation done
          schema:
            type: string
      summary: Recalculate matches
      tags:
      - Admin
  /mmr/matches:
    get:
      description: Get all matches
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/view.MatchDetails'
            type: array
      summary: Get matches
      tags:
      - Matches
    post:
      consumes:
      - application/json
      description: Submit a match for MMR calculation
      parameters:
      - description: Match object
        in: body
        name: match
        required: true
        schema:
          $ref: '#/definitions/view.Match'
      produces:
      - application/json
      responses:
        "200":
          description: match submitted
          schema:
            type: string
      summary: Submit a match
      tags:
      - Matches
  /stats/leaderboard:
    get:
      consumes:
      - application/json
      description: Get leaderboard stats including wins, loses, and MMR of users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/repos.LeaderboardEntry'
            type: array
      summary: Get leaderboard stats
      tags:
      - Leaderboard
swagger: "2.0"
