basePath: /api/v1
definitions:
  mmr.Match:
    properties:
      team1:
        $ref: '#/definitions/mmr.MatchTeam'
      team2:
        $ref: '#/definitions/mmr.MatchTeam'
    required:
    - team1
    - team2
    type: object
  mmr.MatchTeam:
    properties:
      member1:
        type: string
      member2:
        type: string
      score:
        type: integer
    required:
    - member1
    - member2
    type: object
  repos.LeaderboardEntry:
    properties:
      loses:
        type: integer
      mmr:
        type: integer
      name:
        type: string
      wins:
        type: integer
    type: object
info:
  contact: {}
paths:
  /mmr/match:
    post:
      consumes:
      - application/json
      description: Submit a match for MMR calculation
      parameters:
      - description: Match object
        in: body
        name: match
        required: true
        schema:
          $ref: '#/definitions/mmr.Match'
      produces:
      - application/json
      responses:
        "200":
          description: match submitted
          schema:
            type: string
      summary: Submit a match
  /stats/leaderboard:
    get:
      consumes:
      - application/json
      description: Get leaderboard stats including wins, loses, and MMR of users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/repos.LeaderboardEntry'
            type: array
      summary: Get leaderboard stats
      tags:
      - Leaderboard
swagger: "2.0"
